package boundry;
import controllers.CartController;
import controllers.FindProductsController;
import entity.Category;
import entity.Product;
import util.BannerUtil;

import java.util.*;

/** A boundary class which deals with
 * the view of browsing and filtering
 * products for user.
 *
 * @author Arshi Siddiqui Promiti
 * @version 1.1
 */
public class FindProductsView
{
    private final FindProductsController findProdcontroller;
    private final CartController cartcontroller;
    private final CustomerView customerview;
    {}

    /**
     * Non-Default Constructor for the class.
     *
     * @param findProdcontroller    ProductController Object
     * @param cartcontroller        CartController Object
     */
    public FindProductsView(FindProductsController findProdcontroller,
                            CartController cartcontroller,
                            CustomerView customerview)
    {
        this.findProdcontroller = findProdcontroller;
        this.cartcontroller = cartcontroller;
        this.customerview = customerview;
    }

    /**
     * Method to for the default browsing function
     * which shows the default browse products by category.
     * This method shows the categories and the products
     * of each category, and shows out of stock products
     * after in stock items per category.
     *
     */
    public void defaultBrowsing()
    {
        List<Category> categories = findProdcontroller.getProductController().getCategoryList();

        Scanner scanner = new Scanner(System.in);

        // Header and SubHeader for the Browse Page
        BannerUtil.printHeader();
        BannerUtil.printSubheader("Browse Products (Default)");

        // for empty category handling
        if (categories.isEmpty())
        {
            System.out.println("No categories available.");
            return;
        }

        // the next two lines of the code is generated by AI
        // products in a single ordered list for easy numbering
        List<Product> allProducts = new ArrayList<>();
        int productNo = 1;

        for (Category category : categories) {
            System.out.println("\nCategory: " + category.getCategoryName());
            List<Product> productsInCategory = findProdcontroller.browseByCategory(category.getCategoryName());
            productsInCategory = sortProductsByAvailability(productsInCategory); // we will sort before showing the list



            if (productsInCategory.isEmpty())
            {
                System.out.println("  (No products in this category)");
            }
            else
            {
                for (Product p : productsInCategory)
                {
                    String stockLabel = (p.getQuantity() > 0) ? "" : " (Product Out of Stock)";
                    System.out.printf("  %d. %s%s%n", productNo, p.getName(), stockLabel);
                    allProducts.add(p);
                    productNo++;
                }
            }
        }

            // user options at the end of the screen
            System.out.println("1. View Product");
            System.out.println("2. Filter Products");
            System.out.println("3. View Cart");
            System.out.println("4. Back");      // Need to refine
            System.out.print("Enter your choice (1-4): ");

            // user choice
            String choice = scanner.nextLine().trim();

        switch (choice) {
            case "1":
                if (allProducts.isEmpty()) {
                    System.out.println("No products to view.");
                    System.out.println("Press Enter to continue..");
                    scanner.nextLine();
                } else {
                    viewProductByNumber(allProducts);
                }
                break;
            case "2":
                filterProducts();
                break;
            case "3":
                CartView cartView = new CartView(cartcontroller, customerview);
                cartView.viewCart(this);
                break;
            case "4":
                return;
            default:
                System.out.println("Invalid choice. Please enter a number between 1–4.");
                break;
        }

    }

    /**
     * Method which takes input from the user to view the
     * product details of one selected product no. from
     * the list of products.
     *
     * @param   allProducts      List of Product objects
     *
     */
    public void viewProductByNumber(List<Product> allProducts)
    {
        Scanner scanner = new Scanner(System.in);

        System.out.print("\nEnter Product No to View Product Details:");
        String input = scanner.nextLine().trim();

        int productIndex;
        try
        {
            productIndex = Integer.parseInt(input);
        }
        catch (NumberFormatException e)
        {
            System.out.println("Invalid input. Please enter a valid number.");
            System.out.println("Press Enter to continue...");
            scanner.nextLine();
            return;
        }

        if (productIndex < 1 || productIndex > allProducts.size())
        {
            System.out.println("No product found with that number.");
            System.out.println("Press Enter to continue...");
            scanner.nextLine();
            return;
        }

        Product selectedProd = allProducts.get(productIndex - 1);
        showProductDetails(selectedProd);
    }

    /**
     * Method to for showing the details of the product which the customer
     * chooses to view in details.
     *
     * @param   product     Product whose details user wants to see
     *
     */
    public void showProductDetails(Product product)
    {
        BannerUtil.printHeader();
        BannerUtil.printSubheader("Product Details");

        Scanner scanner = new Scanner(System.in);

        System.out.printf("%-20s : %s%n", "Name", product.getName());
        System.out.printf("%-20s : %s%n", "Brand", product.getBrand());
//        System.out.printf("%-20s : %s%n", "Description", product.getDescription());
        System.out.printf("%-20s : $%.2f%n", "Regular Price", product.getPrice());
        System.out.printf("%-20s : $%.2f%n", "VIP Price", product.getMemberPrice());
        System.out.printf("%-20s : %d%n", "Stock Available", product.getQuantity());

        // not showing the Add to Cart Option if the product is out of stock (quantity <=0)
        if (product.getQuantity() <= 0)
        {
            System.out.println("\nThis Product is Currently Out of Stock.");
            System.out.println("Press Enter to go back...");
            scanner.nextLine();
            return;
        }

        // User Options otherwise if the product is in stock.
        System.out.println("\n1. Add to Cart");
        System.out.println("2. Back to Browse");
        System.out.print("Enter your choice: ");

        String choice = scanner.nextLine().trim();

        switch (choice)
        {
            case "1":
                CartView cartView = new CartView(cartcontroller, customerview);
                cartView.addToCartView(product);
                break;
            case "2":
                return;
            default:
                System.out.println("Invalid choice. Please enter a valid choice.");
                scanner.nextLine();
                break;

        }
    }

    /**
     * Method which shows the filtering options menu
     * to the user for choosing.
     *
     */
    public void filterProducts()
    {
        Scanner scanner = new Scanner(System.in);

        BannerUtil.printHeader();
        BannerUtil.printSubheader("Filter Products");

        System.out.println("1. Category");
        System.out.println("2. Subcategory");
        System.out.println("3. Brand");
        System.out.println("4. Price Range");
        System.out.println("5. Availability");
        System.out.print("Enter your choice (1–5): ");
        String choice = scanner.nextLine().trim();

        switch (choice)
        {
            case "1":
                filterByCategory();
                break;
            case "2":
                filterBySubcategory();
                break;
            case "3":
                filterByBrand();
                break;
            case "4":
                filterByPriceRange();
                break;
            case "5":
                filterByAvailability();
                break;
            default:
                System.out.println("Invalid choice. Press Enter to continue...");
                scanner.nextLine();
                break;
        }
    }

    /**
     * Method which shows the views for filter by Category
     * when the user chooses that option.
     *
     */
    public void filterByCategory()
    {
        Scanner scanner = new Scanner(System.in);
        List<Category> categories = findProdcontroller.getProductController().getCategoryList();
        if (categories.isEmpty())
        {
            System.out.println("No categories available.");
            scanner.nextLine();
            return;
        }

        System.out.println("\nSelect Category:");
        for (int i = 0; i < categories.size(); i++)
        {
            System.out.printf("%d. %s%n", i + 1, categories.get(i).getCategoryName());
        }
        System.out.print("Enter choice: ");
        String input = scanner.nextLine().trim();

        int index;
        try
        {
            index = Integer.parseInt(input) - 1;
        }
        catch (NumberFormatException e)
        {
            System.out.println("Invalid input.");
            return;
        }

        if (index < 0 || index >= categories.size())
        {
            System.out.println("Invalid choice.");
            return;
        }

        String selectedCategory = categories.get(index).getCategoryName();
        List<Product> filteredProducts = findProdcontroller.browseByCategory(selectedCategory);

        showFilteredProducts(filteredProducts, scanner);
    }

    /**
     * Method which shows the views for filter by subcategory
     * when the user chooses that option.
     *
     */
    public void filterBySubcategory()
    {
        Scanner scanner = new Scanner(System.in);
        List<Category> categories = findProdcontroller.getProductController().getCategoryList();

        if (categories.isEmpty())
        {
            System.out.println("No categories available.");
        }

        System.out.println("\nSelect Category:");
        for (int i = 0; i < categories.size(); i++)
        {
            System.out.printf("%d. %s%n", i + 1, categories.get(i).getCategoryName());
        }
        System.out.print("Enter choice: ");
        String input = scanner.nextLine().trim();

        int index;
        try
        {
            index = Integer.parseInt(input) - 1;
        }
        catch (NumberFormatException e)
        {
            System.out.println("Invalid input.");
            return;
        }

        if (index < 0 || index >= categories.size())
        {
            System.out.println("Invalid choice.");
            return;
        }

        String selectedCategory = categories.get(index).getCategoryName();
        List<String> subcategories = findProdcontroller.subOfCategory(selectedCategory);

        if (subcategories.isEmpty()) { System.out.println("No subcategories."); return; }

        System.out.println("\nSelect Subcategory:");
        for (int i = 0; i < subcategories.size(); i++) {
            System.out.printf("%d. %s%n", i + 1, subcategories.get(i));
        }
        System.out.print("Enter choice: ");
        int subIndex;
        try { subIndex = Integer.parseInt(scanner.nextLine().trim()) - 1; }
        catch (NumberFormatException e) { System.out.println("Invalid input."); return; }
        if (subIndex < 0 || subIndex >= subcategories.size()) { System.out.println("Invalid choice."); return; }

        List<Product> filteredProducts = findProdcontroller.filterSubcategory(selectedCategory, subcategories.get(subIndex));
        showFilteredProducts(filteredProducts, scanner);

    }

    /**
     * Method which shows the views for filter by brand
     * when the user chooses that option.
     *
     */
    public void filterByBrand()
    {
        Scanner scanner = new Scanner(System.in);
        List<String> brandsList = findProdcontroller.listAllBrands();

        BannerUtil.printHeader();
        BannerUtil.printSubheader("Filter by Brand");

        // check for empty brand list
        if (brandsList.isEmpty()) {
            System.out.println("No brands available.");
            System.out.println("Press Enter to continue...");
            scanner.nextLine();
            return;
        }

        // move on to this part if not empty.
        System.out.println("\nSelect Brand:");
        // listing the brands
        for (int i = 0; i < brandsList.size(); i++) {
            System.out.printf("%d. %s%n", i + 1, brandsList.get(i));
        }

        System.out.print("Enter choice: ");
        String input = scanner.nextLine().trim();

        int index;
        try
        {
            index = Integer.parseInt(input) - 1;
        }
        catch (NumberFormatException e)
        {
            System.out.println("Invalid input.");
            return;
        }

        // check user input of the number entered
        if (index < 0 || index >= brandsList.size()) {
            System.out.println("Invalid choice.");
            return;
        }

        String selectedBrand = brandsList.get(index);
        List<Product> filteredProducts = findProdcontroller.filterByBrand(selectedBrand);

        BannerUtil.printSubheader("Products for Brand: " + selectedBrand);
        showFilteredProducts(filteredProducts, scanner);
    }

    /**
     * Method which shows the views for filter by price range
     * when the user chooses that option.
     *
     */
    public void filterByPriceRange()
    {
        Scanner scanner = new Scanner(System.in);
        BannerUtil.printHeader();
        BannerUtil.printSubheader("Filter Products by Price Range");

        System.out.println("1. Up to AUD $20");
        System.out.println("2. AUD $20 – 30");
        System.out.println("3. AUD $30 – 40");
        System.out.println("4. AUD $40 – 50");
        System.out.println("5. AUD $50 onwards");
        System.out.print("Enter price range to view products (1–5): ");
        String input = scanner.nextLine().trim();

        double minPrice = 0;
        // this part of the code is AI generated
        double maxPrice = Double.MAX_VALUE;

        switch (input)
        {
            case "1":
                maxPrice = 20;
                break;
            case "2":
                minPrice = 20;
                maxPrice = 30;
                break;
            case "3":
                minPrice = 30;
                maxPrice = 40;
                break;
            case "4":
                minPrice = 40;
                maxPrice = 50;
                break;
            case "5":
                minPrice = 50;
                break;
            default:
                System.out.println("Invalid choice. Press Enter to continue...");
                scanner.nextLine();
                return;
        }

        // filtering with the controller method
        List<Product> filteredProducts = findProdcontroller.filterByPriceRange(minPrice, maxPrice);

        BannerUtil.printSubheader("Showing Filtered Products");

        showFilteredProducts(filteredProducts, scanner);
    }

    /**
     * Method which shows the views for filter by availability
     * when the user chooses that option.
     *
     */
    public void filterByAvailability()
    {
        Scanner scanner = new Scanner(System.in);

        BannerUtil.printHeader();
        BannerUtil.printSubheader("Filter by Availability");

        // getting the available product list from controller
        List<Product> availableProducts = findProdcontroller.filterByAvailability();

        showFilteredProducts(availableProducts, scanner);
    }

    /**
     * Method which shows the filtered products list to the user.
     *
     */
    public void showFilteredProducts(List<Product> products, Scanner scanner)
    {
        if (products.isEmpty())
        {
            System.out.println("No products found for this filter.");
            System.out.println("Press Enter to continue...");
            scanner.nextLine();
            return;
        }

        System.out.println("\nFiltered Products:");
        for (int i = 0; i < products.size(); i++)
        {
            System.out.printf("%d. %s%n", i + 1, products.get(i).getName());
        }

        // same method as before
        viewProductByNumber(products);
    }

    /**
     * Method for sorting products in default browsing. In this,
     * in stock products are shown first, then out-of-stock products.
     *
     * @param   products    ArrayList of product objects which needs to be sorted
     *                      by stock quantity.
     */
    private List<Product> sortProductsByAvailability(List<Product> products)
    {
        products.sort(Comparator.comparingInt(p -> p.getQuantity() > 0 ? 0 : 1));
        return products;
    }


}
